dubbo:
  application:
    name: provider-service
  protocol:
    name: tri
  registry:
    address: nacos://localhost:8848
  provider: #https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/security/token-authorization
    token: true
